# Generated by Django 5.2.5 on 2025-11-25 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('hours_open', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('room_number', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('on_campus', models.BooleanField(default=True)),
                ('id_required', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=True)),
                ('outlets', models.BooleanField(default=True)),
                ('windows', models.BooleanField(default=False)),
                ('whiteboard', models.BooleanField(default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_rooms', to='terrier_study.building')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('custom_roomname', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('study_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='terrier_study.studyroom')),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('text', models.TextField(blank=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField(blank=True)),
                ('study_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='terrier_study.studyroom')),
            ],
        ),
    ]
