# Generated by Django 5.2.5 on 2025-11-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrier_study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyroom',
            name='room_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
