# Generated by Django 5.2.5 on 2025-11-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrier_study', '0002_alter_studyroom_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyroom',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
    ]
