# Generated by Django 5.2.5 on 2025-12-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrier_study', '0004_alter_userreview_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('bu_id', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=100)),
            ],
        ),
    ]
