# Generated by Django 5.2.5 on 2025-12-09 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrier_study', '0006_remove_userfavorite_user_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terrier_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
