# Generated by Django 5.2.5 on 2025-11-15 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dadjokes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joke',
            old_name='joke',
            new_name='text',
        ),
    ]
