# Generated by Django 5.2.5 on 2025-10-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
