# Generated by Django 5.2.5 on 2025-10-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='precinct_number',
            field=models.CharField(max_length=5),
        ),
    ]
