# Generated by Django 5.2.5 on 2025-09-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usename',
            new_name='username',
        ),
    ]
