# Generated by Django 5.2.5 on 2025-10-02 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0003_post_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='timestramp',
            new_name='timestamp',
        ),
    ]
